/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesinventorysystem;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author UMAGAGEE
 */
public class Creditors extends javax.swing.JFrame {
    Connection con = null;
PreparedStatement pre= null;
ResultSet res = null;
Statement stm=null;
int rest_drug ;
String sql1;
String sql2;
String sql3;

    /**
     * Creates new form Creditors
     */
    public Creditors() {
        initComponents();
        con=ConnectionToDatabase.conn();
        setLocationRelativeTo(null);
        supplier();
        refresh();
        showCreditor();
        
         Date date = new Date();
          jDateChooserPayment.setDate(date);
        
        jLabelTobePaid.hide();
        jLabelPaid.hide();
        jLabelLeft.hide();
        jLabelCreditor.hide();
        jLabelID.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        druglist = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        total_amount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        total_amount1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelTobePaid = new javax.swing.JLabel();
        jLabelPaid = new javax.swing.JLabel();
        jLabelLeft = new javax.swing.JLabel();
        jLabelCreditor = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPaying = new javax.swing.JTextField();
        btnPaid = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jDateChooserPayment = new com.toedter.calendar.JDateChooser();
        jComboBoxPaidBy1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Andalus", 1, 40)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("CREDITORS");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 40));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...." }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 177, -1));

        jButton4.setBackground(new java.awt.Color(51, 255, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("GHS");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("GHS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 90));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        druglist.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        druglist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        druglist.setRowHeight(20);
        druglist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                druglistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(druglist);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 195, 560, 420));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total_amount.setBackground(new java.awt.Color(255, 255, 255));
        total_amount.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        total_amount.setText("00.0");
        total_amount.setOpaque(true);
        jPanel5.add(total_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 10, 280, 59));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total  Creditor: ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, -1));

        total_amount1.setBackground(new java.awt.Color(255, 255, 255));
        total_amount1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        total_amount1.setText("00.0");
        total_amount1.setOpaque(true);
        jPanel5.add(total_amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 260, 66));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Supplier:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 120, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 930, 90));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amount to be Paid:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Received No.:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Amount Paid:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Amount Left:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        jLabelID.setBackground(new java.awt.Color(255, 255, 255));
        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelID.setText("Received No.:");
        jLabelID.setOpaque(true);
        jPanel4.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, -1));

        jLabelTobePaid.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTobePaid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTobePaid.setText("Amount to be Paid:");
        jLabelTobePaid.setOpaque(true);
        jPanel4.add(jLabelTobePaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, -1));

        jLabelPaid.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPaid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPaid.setText("Amount Paid:");
        jLabelPaid.setOpaque(true);
        jPanel4.add(jLabelPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 180, -1));

        jLabelLeft.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLeft.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelLeft.setText("Amount Left:");
        jLabelLeft.setOpaque(true);
        jPanel4.add(jLabelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, -1));

        jLabelCreditor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCreditor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCreditor.setText("Creditor:");
        jLabelCreditor.setOpaque(true);
        jPanel4.add(jLabelCreditor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Creditor:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("GHS:");

        txtPaying.setEditable(false);
        txtPaying.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPaying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayingActionPerformed(evt);
            }
        });
        txtPaying.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayingKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPayingKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPayingKeyTyped(evt);
            }
        });

        btnPaid.setBackground(new java.awt.Color(51, 255, 204));
        btnPaid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPaid.setText("Paid");
        btnPaid.setEnabled(false);
        btnPaid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaidMouseExited(evt);
            }
        });
        btnPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaidActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 255, 204));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("Print");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 255, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel65.setText("Paid By");

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel60.setText("Date Paid:");

        jComboBoxPaidBy1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxPaidBy1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Cash", "Cheque" }));
        jComboBoxPaidBy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaidBy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPaying))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(jComboBoxPaidBy1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jDateChooserPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel60))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaying, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPaidBy1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaid)
                    .addComponent(jButton6)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 330, 170));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 370, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setBackground(Color.red);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(new Color(0x33FFCC));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        refresh();
         clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        DecimalFormat df = new  DecimalFormat("#.##");
        String user = jComboBox1.getSelectedItem().toString();

        try{

            //Total Sales
            String sql = "select * from stock where supplier='"+user+"' ";
            pre=con.prepareStatement(sql);
            res=pre.executeQuery();
            double amount=0;
            while(res.next()){

                amount += Double.parseDouble(res.getString("amt_left"));
                total_amount1.setText(String.valueOf(df.format(amount)));
            }

        }
        catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void druglistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_druglistMouseClicked
  int index;
        
        TableModel model=druglist.getModel();

        int selectedRow = druglist.getSelectedRow();
        index =Integer.parseInt( model.getValueAt(selectedRow, 0).toString());

        String sql = "select * from stock where receiving_number='"+index+"' " ;
        try{
            pre=con.prepareStatement(sql);
            res=pre.executeQuery();
            if(res.next()){
                
                
               
                
                String id = res.getString("receiving_number");
                jLabelID.setText(id);
                jLabelID.show();

             
                
                String amt_to_be_paid = res.getString("amt_to_be_paid");
                jLabelTobePaid.setText(amt_to_be_paid);
                jLabelTobePaid.show();

                String amt_paid = res.getString("amt_paid");
                jLabelPaid.setText(amt_paid);
                jLabelPaid.show();

                String amt_left = res.getString("amt_left");
                jLabelLeft.setText(amt_left);
                jLabelLeft.show();

                
                String supplier = res.getString("supplier");
                jLabelCreditor.setText(supplier);
                jLabelCreditor.show();

                
                 
               
                txtPaying.setEditable(true);   
                
                
                
                    }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }
    }//GEN-LAST:event_druglistMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        refresh();
        showCreditor();
        total_amount1.setText("00.0");
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnPaidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaidMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaidMouseEntered

    private void btnPaidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaidMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaidMouseExited

    private void btnPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaidActionPerformed
 int pos = jComboBoxPaidBy1.getSelectedIndex();
        
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            if(pos==0){
             JOptionPane.showMessageDialog(null, "Please Select Payment Type");
            }else{
            
            
                         try{
                             
                String paid = jLabelPaid.getText();
                double numpaid = Double.parseDouble(paid);

                String amt_left=jLabelLeft.getText().trim();
                double numLeft = Double.parseDouble(amt_left);
                
                String amt_paying=txtPaying.getText().trim();
                double numPaying = Double.parseDouble(amt_paying); 
                
                double newAmount = numLeft - numPaying;
                
                double totalPaid = numpaid + numPaying;

String sql= "update stock set "
 + " amt_paid=?,amt_left=?,paid_by=?,payment_date=?"
        + " where receiving_number='"+jLabelID.getText().trim()+"' ";

                pre=con.prepareStatement(sql);
                 pre.setDouble(1, totalPaid);
                 pre.setDouble(2, newAmount);
                 pre.setString(3, jComboBoxPaidBy1.getSelectedItem().toString());
                 SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                String paymentDate=dateFormat.format(jDateChooserPayment.getDate());
                pre.setString(4,paymentDate);
                  pre.executeUpdate();
                  
                JOptionPane.showMessageDialog(null, "Amount Paid");
                showCreditor();
                refresh();
                clear();
                 }catch(HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
        }
        }
    }//GEN-LAST:event_btnPaidActionPerformed

    private void txtPayingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayingActionPerformed

    private void txtPayingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayingKeyPressed
        //Preventing user from entering a String
        String number =txtPaying.getText().trim();
        int l=number.length();
        if((evt.getKeyChar() >= '0' && evt.getKeyChar()<='9' || evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)){
            txtPaying.setEditable(true);
        }else{
            //  txtContact.setEditable(false);

            JOptionPane.showMessageDialog(null, "*Please Enter only digits(0-9)");
            txtPaying.setText("");
        }
    }//GEN-LAST:event_txtPayingKeyPressed

    private void txtPayingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayingKeyReleased
     try{
                 String amt_left=jLabelLeft.getText().trim();
                double numLeft = Double.parseDouble(amt_left);
                String amt_paying=txtPaying.getText().trim();
                double numPaying = Double.parseDouble(amt_paying);


          
          if(numPaying>numLeft){
                JOptionPane.showMessageDialog(null,"Amount Paying should not be more than Amount Owing");
          txtPaying.setText("");
          btnPaid.setEnabled(false);
          }else{
              
            btnPaid.setEnabled(true);
          }
             
         }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null, e.getMessage());
         }
    }//GEN-LAST:event_txtPayingKeyReleased

    private void txtPayingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayingKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayingKeyTyped

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
          
            URL   url=this.getClass().getClassLoader().getResource("logo/Share.jpg");  
            
            HashMap param =  new HashMap();

        //    param.put("myImg", url);



InputStream jasperStream = getClass().getResourceAsStream("/report/CreditorsReport.jasper");
//JasperReport jr =  JasperCompileManager.compileReport(getClass().getResourceAsStream("/reports/memberReport.jrxml"));jasper
 //JasperReport jr =  JasperCompileManager.compileReport(jd);
  JasperReport jr =  (JasperReport) JRLoader.loadObject(jasperStream);
  JasperPrint jp  = JasperFillManager.fillReport(jr, param, con);
  
  JasperViewer jv = new JasperViewer(jp,false); 
  jv.setVisible(true);
    
    

    } catch ( JRException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
        
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBoxPaidBy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaidBy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPaidBy1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creditors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creditors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creditors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creditors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creditors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaid;
    private javax.swing.JTable druglist;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxPaidBy1;
    private com.toedter.calendar.JDateChooser jDateChooserPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCreditor;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelLeft;
    private javax.swing.JLabel jLabelPaid;
    private javax.swing.JLabel jLabelTobePaid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel total_amount;
    private javax.swing.JLabel total_amount1;
    public javax.swing.JTextField txtPaying;
    // End of variables declaration//GEN-END:variables

   private void refresh(){
     DecimalFormat df = new  DecimalFormat("#.##");
        String user = jComboBox1.getSelectedItem().toString();

        try{

            //Total Sales
            String sql = "select * from stock where amt_left>'0' ";
            pre=con.prepareStatement(sql);
            res=pre.executeQuery();
            double amount=0;
            while(res.next()){

                amount += Double.parseDouble(res.getString("amt_left"));
                total_amount.setText(String.valueOf(df.format(amount)));
            }

        }
        catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }
  }
 
     void supplier(){
         String sql = "select name from supplier";
        try{
            pre=con.prepareStatement(sql);
            res=pre.executeQuery();
            while(res.next()){
                jComboBox1.addItem(res.getString("name"));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        } 
    
    }
   
      void showCreditor(){
         String sql = "select receiving_number,amt_to_be_paid,amt_paid,amt_left,supplier from stock where amt_left>'0' ";
                     try{
                
        pre=con.prepareStatement(sql);
        res=pre.executeQuery();
        druglist.setModel(DbUtils.resultSetToTableModel(res)); 

    }
    catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
    
    }
      
      
      
      void clear(){
      jLabelTobePaid.hide();
        jLabelPaid.hide();
        jLabelLeft.hide();
        jLabelCreditor.hide();
        jLabelID.hide();
        txtPaying.setEditable(false);
        txtPaying.setText("");
        btnPaid.setEnabled(false);
        jComboBoxPaidBy1.setSelectedIndex(0);
         Date date = new Date();
          jDateChooserPayment.setDate(date);
      }
}
