/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesinventorysystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Steve
 */
public class Profile extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
 String imagePath=null;
    /**
     * Creates new form Registration
     */
    public Profile() {
        initComponents();
      conn=ConnectionToDatabase.conn();
        setLocationRelativeTo(null);
       // jLabel13.setText(home.jLabelUsername.getText());
       refresh();
    }
    
     //Function to Resize Image to fit into Jlabel 
    public ImageIcon ResizeImage(String imagePath,byte[] pic){
    ImageIcon myImage = null;
     if(imagePath!=null){
      myImage=new ImageIcon(imagePath);
     }
     else{
     myImage=new ImageIcon(pic);
     }
     
     Image img1 = myImage.getImage();
     Image img2 = img1.getScaledInstance(jLabel3.getWidth(),jLabel3.getHeight(),Image.SCALE_SMOOTH);
     ImageIcon image =new ImageIcon(img2);
     return image;
    };
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lblPicture = new javax.swing.JPanel();
        jDateChooserBirthday = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtSn = new javax.swing.JTextField();
        txtfn = new javax.swing.JTextField();
        jPanel41 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.setPreferredSize(new java.awt.Dimension(89, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 310, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 640, 70));

        lblPicture.setBackground(new java.awt.Color(0, 51, 51));
        lblPicture.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPicture.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        lblPicture.add(jDateChooserBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 236, 29));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("FirstName");
        lblPicture.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LastName");
        lblPicture.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date of Birth");
        lblPicture.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact");
        lblPicture.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username");
        lblPicture.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        txtUser.setEditable(false);
        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });
        lblPicture.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 240, 30));

        txtContact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactKeyPressed(evt);
            }
        });
        lblPicture.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 240, 30));

        txtSn.setEditable(false);
        txtSn.setBackground(new java.awt.Color(255, 255, 255));
        txtSn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPicture.add(txtSn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 240, 30));

        txtfn.setEditable(false);
        txtfn.setBackground(new java.awt.Color(255, 255, 255));
        txtfn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPicture.add(txtfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 240, 30));

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Picture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setBackground(new java.awt.Color(0, 51, 51));
        jButton22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Browse");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel41.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 40));

        jLabel3.setOpaque(true);
        jPanel41.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 160));

        lblPicture.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 230, 250));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Position");
        lblPicture.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        txtPosition.setEditable(false);
        txtPosition.setBackground(new java.awt.Color(255, 255, 255));
        txtPosition.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPosition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPositionKeyReleased(evt);
            }
        });
        lblPicture.add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 240, 30));

        jPanel1.add(lblPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 640, 340));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("PROFILE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 680, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int p = JOptionPane.showConfirmDialog(null, ", Are you sure you want to UPDATE your Profile? Confirm and Proceed ","",JOptionPane.YES_NO_OPTION);
        if(p==0){          
        if(txtfn.getText().equals("") || txtSn.getText().equals("")
                    || jDateChooserBirthday.getDate()==null || txtContact.getText().equals("")
                     || txtUser.getText().equals("")
                    )    {
            JOptionPane.showMessageDialog(null, "Complete  Information", "Missing Information", 2);
        } else if( imagePath !=null){

                try{

                    String sql= "update worker set"
                    + " firstname=?,lastname=?,birth_date=?,contact=?,image=?"
                    + "where username='"+txtUser.getText().trim()+"'";

                    pst=conn.prepareStatement(sql);
                    pst.setString(1, txtfn.getText().trim());
                    pst.setString(2, txtSn.getText().trim());
                    SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                    String dateAdmitted=dateFormat.format(jDateChooserBirthday.getDate());
                    pst.setString(3,dateAdmitted);
                    pst.setString(4, txtContact.getText().trim());
               
                    InputStream img;
                    img = new FileInputStream(new File(imagePath));
                    pst.setBlob(5,img);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Updated");
                  refresh();

                }catch(HeadlessException | FileNotFoundException | SQLException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                //Updating without Image
            }else if( imagePath ==null){

                try{

                    String sql= "update worker set"
                    + " firstname=?,lastname=?,birth_date=?,contact=?"
                    + "where username='"+txtUser.getText().trim()+"'";

                    pst=conn.prepareStatement(sql);
                    pst.setString(1, txtfn.getText().trim());
                    pst.setString(2, txtSn.getText().trim());
                    SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                    String dateAdmitted=dateFormat.format(jDateChooserBirthday.getDate());
                    pst.setString(3,dateAdmitted);
                    pst.setString(4, txtContact.getText().trim());
               
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Updated");
                  refresh();

                }catch(HeadlessException  | SQLException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyPressed
              //Preventing user from entering a String  
        String number =txtContact.getText().trim();
        int l=number.length();
        if((evt.getKeyChar() >= '0' && evt.getKeyChar()<='9' || evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)){
            txtContact.setEditable(true);
        }else{
            txtContact.setEditable(false);
          // txtContact.setText("");
             JOptionPane.showMessageDialog(null, "*Please Enter only digits(0-9)");
        }
    }//GEN-LAST:event_txtContactKeyPressed

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyReleased

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        try{
            JFileChooser file = new JFileChooser();
            file.setCurrentDirectory(new File(System.getProperty("user.home")));

            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png");

            file.addChoosableFileFilter(filter);
            int result =file.showSaveDialog(null);
            if(result==JFileChooser.APPROVE_OPTION){
                File selectedFile=file.getSelectedFile();
                String path=selectedFile.getAbsolutePath();
                jLabel3.setIcon(ResizeImage(path,null));
                imagePath=path;
            }
            else{
                JOptionPane.showMessageDialog(null, "No file");
            }
        }
        catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Error!");

        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void txtPositionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPositionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private com.toedter.calendar.JDateChooser jDateChooserBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel41;
    public javax.swing.JPanel lblPicture;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSn;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtfn;
    // End of variables declaration//GEN-END:variables

void clear(){
 txtfn.setText("");
 txtUser.setText("");
txtSn.setText("");
jDateChooserBirthday.setDate(null);
txtContact.setText("");
 jButton2.setEnabled(false);
}

void refresh(){
     try{
                String sql ="select * from worker where username='"+LogIn.UserName.getText()+"' ";

                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    String username = rs.getString("username");
                    txtUser.setText(username);

                    String firstname = rs.getString("firstname");
                    txtfn.setText(firstname);

                    String Lname = rs.getString("lastname");
                    txtSn.setText(Lname);


                    String position = rs.getString("position");
                    txtPosition.setText(position);

                    Date dob = rs.getDate("birth_date");
                    jDateChooserBirthday.setDate(dob);

                    String contact = rs.getString("contact");
                    txtContact.setText(contact);

                 

                    byte[]pic=rs.getBytes("image");
                    if(pic == null){
                        jLabel3.setIcon(null);
                    }else{
                        ImageIcon image=new ImageIcon(pic);
                        Image im= image.getImage();
                        Image myimg=im.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon newImage=new ImageIcon(myimg);
                        jLabel3.setIcon(newImage);
                    }

             

                }

            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

}
}
