/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesinventorysystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static org.codehaus.groovy.tools.shell.util.Preferences.clear;

/**
 *
 * @author UMAGAGEE
 */
public class user extends javax.swing.JFrame {
       SimpleDateFormat dd;
    Connection con = null;
    PreparedStatement ps= null;
    ResultSet rs = null;
     Statement stm=null;
    String imagePath=null;

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        con=ConnectionToDatabase.conn();
        setLocationRelativeTo(null);
        jLabel30.hide();
    }
    
      
    //Function to Resize Image to fit into Jlabel 
    public ImageIcon ResizeImage(String imagePath,byte[] pic){
    ImageIcon myImage = null;
     if(imagePath!=null){
      myImage=new ImageIcon(imagePath);
     }
     else{
     myImage=new ImageIcon(pic);
     }
     
     Image img1 = myImage.getImage();
     Image img2 = img1.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
     ImageIcon image =new ImageIcon(img2);
     return image;
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSetting = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        textSearch9 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jPanel40 = new javax.swing.JPanel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBoxPosition = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jDateChooserBirthday = new com.toedter.calendar.JDateChooser();
        jPanel20 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanel41 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelSetting.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSetting.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelSetting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(0, 51, 51));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Item Details");
        jPanel18.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 66, -1, 40));

        jLabel58.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Search By:");
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 66, -1, 40));

        jComboBox7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tittle" }));
        jPanel18.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 66, 182, 40));

        textSearch9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textSearch9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSearch9KeyTyped(evt);
            }
        });
        jPanel18.add(textSearch9, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 72, 195, 31));

        jPanel19.setBackground(new java.awt.Color(0, 51, 51));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Administrator Setting");
        jPanel19.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 11, -1, 40));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        jPanel18.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 161, 31));

        jPanelSetting.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 60));

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registration Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFNameKeyTyped(evt);
            }
        });
        jPanel40.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 161, 31));

        txtLName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLNameKeyTyped(evt);
            }
        });
        jPanel40.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 161, 31));

        txtUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        jPanel40.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 161, 31));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 51, 51));
        jLabel30.setText("User Name:");
        jPanel40.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, 30));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel31.setText("First Name:");
        jPanel40.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 30));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel32.setText("Last Name:");
        jPanel40.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel33.setText("Postion:");
        jPanel40.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, 30));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel34.setText("Password:");
        jPanel40.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 30));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel37.setText("Confirm Password:");
        jPanel40.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 190, 30));

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel40.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 160, 30));

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel40.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, 30));

        jComboBoxPosition.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBoxPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Admin", "Salesperson", "Assistant", "other" }));
        jPanel40.add(jComboBoxPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, 30));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel49.setText("User Name:");
        jPanel40.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));

        jLabel64.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel64.setText("Contact:");
        jPanel40.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 30));

        txtContact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });
        jPanel40.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 161, 31));

        jLabel65.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel65.setText("Birth Date:");
        jPanel40.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));
        jPanel40.add(jDateChooserBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 170, 29));

        jPanelSetting.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 420));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton21.setBackground(new java.awt.Color(0, 51, 51));
        jButton21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Find");
        jPanel20.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 80, -1));

        jButton57.setBackground(new java.awt.Color(0, 51, 51));
        jButton57.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton57.setForeground(new java.awt.Color(255, 255, 255));
        jButton57.setText("clear");
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 40));

        jButton58.setBackground(new java.awt.Color(0, 51, 51));
        jButton58.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton58.setForeground(new java.awt.Color(255, 255, 255));
        jButton58.setText("Delete");
        jButton58.setEnabled(false);
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 40));

        jButton59.setBackground(new java.awt.Color(0, 51, 51));
        jButton59.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton59.setForeground(new java.awt.Color(255, 255, 255));
        jButton59.setText("Save");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 110, 40));

        jButton23.setBackground(new java.awt.Color(0, 51, 51));
        jButton23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Update");
        jButton23.setEnabled(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 110, 40));

        jPanelSetting.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 270, 120));

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Picture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setBackground(new java.awt.Color(0, 51, 51));
        jButton22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Browse");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel41.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, 40));

        jLabel1.setOpaque(true);
        jPanel41.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 180));

        jPanelSetting.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 270, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanelSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSearch9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearch9KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearch9KeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String search=txtSearch.getText().toUpperCase().trim();
        String sql="Select * from worker where username like '"+search+"%' OR firstname like '"+search+"%' OR lastname like '"+search+"%'  ";

        try{
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            if(rs.next()){
                String id = rs.getString("username");
                txtUsername.setText(id);

                String firstName = rs.getString("firstname");
                txtFName.setText(firstName);

                String lastname = rs.getString("lastname");
                txtLName.setText(lastname);

                String pos = rs.getString("position");
                jComboBoxPosition.setSelectedItem(pos);

                String contact = rs.getString("contact");
                txtContact.setText(contact);

                Date birth_date = rs.getDate("birth_date");
                jDateChooserBirthday.setDate(birth_date);

                byte[]pic=rs.getBytes("image");

                if(pic == null){

                }else{
                    ImageIcon image=new ImageIcon(pic);
                    Image im= image.getImage();
                    Image myimg=im.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon newImage=new ImageIcon(myimg);
                    jLabel1.setIcon(newImage);
                }
                txtUsername.setEditable(false);
                jButton23.setEnabled(true);
                jButton58.setEnabled(true);
                jPasswordField1.setEditable(false);
                jPasswordField2.setEditable(false);
                jButton59.setEnabled(false);

            }else{
                clearSettings();
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar())&& !Character.isSpaceChar(evt.getKeyChar())){

        }else if(txtFName.getText().trim().length()==0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtFNameKeyTyped

    private void txtLNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar())&& !Character.isSpaceChar(evt.getKeyChar())){

        }else if(txtLName.getText().trim().length()==0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtLNameKeyTyped

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar())&& !Character.isSpaceChar(evt.getKeyChar())){

        }else if(txtUsername.getText().trim().length()==0 && Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed

    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        Font f = new Font("serif", Font.PLAIN,20);
        Graphics g;
        jLabel30.show();
        String pass = jPasswordField2.getText().trim();
        String cpass = jPasswordField1.getText().trim();
        try{
            if(pass.equals(cpass)){
                
                jLabel30.setForeground(Color.decode("#009900"));
                jLabel30.setText("Password Match");
                jButton59.setEnabled(true);
            }else{
                jLabel30.setText("* Please Password don't Match");
                jLabel30.setForeground(Color.RED);
                jButton59.setEnabled(false);
            }

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactKeyTyped

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        clearSettings();
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "You can't Recover it, Are you sure you want to DELETE this Member? Confirm and Proceed ","",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql = "delete from worker where username='" + txtUsername.getText().trim() + "' ";
            try {
                ps = con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Person has been deleted Successfully", "Success Operation", 1);
                clearSettings();

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 2);
                clearSettings();
            }
        }
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        String storePassword=jPasswordField2.getText();

        //Hashing Password
        PasswordHashing hp=new PasswordHashing();
        String hashedPassword=hp.hashPassword(storePassword, storePassword);

        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Save record?","Save Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            if(txtUsername.getText().equals("") || txtFName.getText().equals("") ||txtLName.getText().equals("")
                || jComboBoxPosition.getSelectedItem().equals("Select...")||jPasswordField2.getText().equals("")){
                JOptionPane.showMessageDialog(null,("One or More fields is empty"));
            }else{

                if(imagePath==null){
                    try{

                        ps=con.prepareStatement("INSERT INTO worker "
                            + "(username,firstname,lastname,position,birth_date,contact,password) values(?,?,?,?,?,?,?)");

                        ps.setString(1, txtUsername.getText().trim().toUpperCase());
                        ps.setString(2, txtFName.getText().trim().toUpperCase());
                        ps.setString(3, txtLName.getText().trim().toUpperCase());
                        ps.setString(4, jComboBoxPosition.getSelectedItem().toString().trim());
                        SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                        String dateAdmitted=dateFormat.format(jDateChooserBirthday.getDate());
                        ps.setString(5,dateAdmitted);
                        ps.setString(6, txtContact.getText().trim());

                        ps.setString(7, hashedPassword);

                        ps.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Data is saved successfully");
                        clearSettings();

                    }
                    catch( HeadlessException | SQLException e){
                        JOptionPane.showMessageDialog(null,e.getMessage());
                        //clearSettings();
                    }

                }else{

                    try{

                        ps=con.prepareStatement("INSERT INTO worker "
                            + "(username,firstname,lastname,position,birth_date,contact,password,image) values(?,?,?,?,?,?,?,?)");

                        ps.setString(1, txtUsername.getText().trim().toUpperCase());
                        ps.setString(2, txtFName.getText().trim().toUpperCase());
                        ps.setString(3, txtLName.getText().trim().toUpperCase());
                        ps.setString(4, jComboBoxPosition.getSelectedItem().toString().trim());
                        SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                        String dateAdmitted=dateFormat.format(jDateChooserBirthday.getDate());
                        ps.setString(5,dateAdmitted);
                        ps.setString(6, txtContact.getText().trim());
                        ps.setString(7, hashedPassword);
                        InputStream img;
                        img = new FileInputStream(new File(imagePath));
                        ps.setBlob(8,img);

                        ps.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Data is saved successfully");
                        clearSettings();

                    }
                    catch( HeadlessException | FileNotFoundException | SQLException e){
                        JOptionPane.showMessageDialog(null,e.getMessage());
                        // clear();
                    }
                }
            }

        }
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        if(imagePath==null){

            try{

                String sql= "update worker set firstname=?,lastname=?,position=?,birth_date=?,contact=?"
                + "where username='"+txtUsername.getText().toUpperCase().trim()+"' ";

                ps=con.prepareStatement(sql);
                ps.setString(1, txtFName.getText());
                ps.setString(2, txtLName.getText());
                ps.setString(3, jComboBoxPosition.getSelectedItem().toString());
                SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                String dateAdmitted=dateFormat.format(jDateChooserBirthday.getDate());
                ps.setString(4,dateAdmitted);
                ps.setString(5, txtContact.getText().trim());

                ps.executeUpdate();
                clearSettings();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else{
            try{
                String sql= "update worker set firstname=?,lastname=?,position=?,,birth_date=?,contact=?image=?"
                + "where username='"+txtUsername.getText().toUpperCase().trim()+"' ";

                ps=con.prepareStatement(sql);
                ps.setString(1, txtFName.getText());
                ps.setString(2, txtLName.getText());
                ps.setString(3, jComboBoxPosition.getSelectedItem().toString());
                SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                String dateAdmitted=dateFormat.format(jDateChooserBirthday.getDate());
                ps.setString(4,dateAdmitted);
                ps.setString(5, txtContact.getText().trim());
                InputStream img;
                img = new FileInputStream(new File(imagePath));
                ps.setBlob(6,img);
                ps.executeUpdate();
                clearSettings();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(HeadlessException | FileNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        try{
            JFileChooser file = new JFileChooser();
            file.setCurrentDirectory(new File(System.getProperty("user.home")));

            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png");

            file.addChoosableFileFilter(filter);
            int result =file.showSaveDialog(null);
            if(result==JFileChooser.APPROVE_OPTION){
                File selectedFile=file.getSelectedFile();
                String path=selectedFile.getAbsolutePath();
                jLabel1.setIcon(ResizeImage(path,null));
                imagePath=path;
            }
            else{
                JOptionPane.showMessageDialog(null, "No file");
            }
        }
        catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Error!");

        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBoxPosition;
    private com.toedter.calendar.JDateChooser jDateChooserBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanelSetting;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField textSearch9;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

void clearSettings(){
     Date date = new Date();
    jDateChooserBirthday.setDate(date);
    jButton59.setEnabled(true);
    txtContact.setText("");
    txtSearch.setText("");
    jPasswordField1.setText("");
    jPasswordField2.setText("");
    txtUsername.setText(" ");
     txtFName.setText(" ");
     txtLName.setText(" ");
     jComboBoxPosition.setSelectedIndex(0);
     jButton23.setEnabled(false);
    jButton58.setEnabled(false);
    jPasswordField1.setEditable(true);
 jPasswordField2.setEditable(true);
 jLabel1.setIcon(null);
 jLabel30.hide();
 txtUsername.setEditable(true);
               

}
}
